#!/bin/bash
fcm=/users/global/rjel/bin/fcm-2014.06.0/bin/fcm
wd=`pwd`

. $wd/usualSettings
echo "$1/trunk/etc/fcm-make/make.cfg"
$fcm make -f "$1/trunk/etc/fcm-make/make.cfg" -C compiled
ln -sfn $wd/compiled/build/bin/jules.exe

