#!/bin/bash

wd=`pwd`

source ../cfg
cp -f ../docs/namelists/* .

sed -i -e 's|CLIM_OUTPUT_DIR|'"$clim_output_dir"'|g' *.nml
sed -i -e 's|JULES_OUTPUT_DIR|'"$jules_output_dir"'|g' *.nml


module load intel/15.0
echo fcm make -f "$1/etc/fcm-make/make-fast.cfg"  
fcm make -f "$1/etc/fcm-make/make-fast.cfg" -C compiled

ln -sfn $wd/compiled/build/bin/jules.exe

